
apiVersion: v1
kind: Service
metadata:
  name: node-apps
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: node-apps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-apps
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-apps
  template:
    metadata:
      labels:
        app: node-apps
    spec:
      containers:
      - name: node-apps
        image: system/node-apps:1.5
        ports:
        - containerPort: 3000
